Model:
  name: RdfModel
  origin: store
  source: BlueBrainNexus
  context:
    iri: "https://bbp.neuroshapes.org"
    bucket: "neurosciencegraph/datamodels"

Store:
  name: BlueBrainNexus
  endpoint: https://staging.nexus.ocp.bbp.epfl.ch/v1
  bucket: dke/embedder_catalog
  searchendpoints:
    sparql:
      endpoint: "https://bluebrain.github.io/nexus/vocabulary/defaultSparqlIndex"
  versioned_id_template: "{x.id}?rev={x._store_metadata._rev}"
  file_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-store/file-to-resource-mapping.hjson

Resolvers:
  ontology:
    - resolver: OntologyResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: terms
          bucket: neurosciencegraph/datamodels
      result_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-resolver/term-to-resource-mapping.hjson
  agent:
    - resolver: AgentResolver
      origin: store
      source: BlueBrainNexus
      targets:
        - identifier: agents
          bucket: bbp/agents
      result_resource_mapping: https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/configurations/nexus-resolver/agent-to-resource-mapping.hjson

Formatters:
  identifier: https://bbp.epfl.ch/neurosciencegraph/data/{}/{}
