language: python

python:
  - "3.7"
  - "3.8"

install:
  # Get Neo4j from a third party repo and install
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo add-apt-repository universe
  - sudo apt-get install neo4j=1:4.2.3
  # Download the graph data science lib
  - wget https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/neo4j-graph-data-science-1.5.1-standalone.zip
  - unzip neo4j-graph-data-science-1.5.1-standalone.zip
  - sudo cp neo4j-graph-data-science-1.5.1.jar /var/lib/neo4j/plugins/
  # Get Miniconda from a third party repo and install
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create a new virtual env with graph-tool and faiss-gpu
  - conda create --name test-environment -c conda-forge graph-tool faiss-gpu python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  # Install the rest of the dependencies
  - pip install .[dev]
  # Configure the Neo4j database
  - sudo neo4j-admin set-initial-password neo4j
  - echo 'dbms.connector.bolt.listen_address=0.0.0.0:7687' | sudo tee -a /etc/neo4j/neo4j.conf
  - echo 'dbms.security.procedures.unrestricted=gds.*' | sudo tee -a /etc/neo4j/neo4j.conf
  - echo 'dbms.security.procedures.whitelist=gds.*' | sudo tee -a /etc/neo4j/neo4j.conf
  - cat /etc/neo4j/neo4j.conf
  # Start a db instance and wait (it takes time to start)
  - sudo service neo4j restart
  - sleep 60

services:
  - neo4j

script:
  - pytest --cov=./bluegraph

after_success:
  - codecov

deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
  user: bbp.opensource
  password:
    secure: nItO6zvjqabsDOVyqj4k4V7dJXKz5FN9mkzlunTpZjJDQKISyN+lfDbrpjKihZyToY4fP5XsPnDK6zInnVFmjLDDrAsNh4IaNdU10HSmvGpTxCr3ecAMnLrBHHQrs7LplsjorSFwGjpaGr+M0PD3axi+itiMtTnuwaVH4CS0ywKMqt5575Wn8hdgJ7x/OglbA16DjhyoupdKGBdSv7HhB7AujOjQOfbnTWjuMVcjF3FFoARZuKdlmyDybMsujwgaTUxSLBVE8FqRifcukCAAmTn1O3UYNOY53QK0NsPYNvjRWAK9S/uMzOTduX69zDl7ChBtrsaplfdpqGv4U4QagIr5YgdnxVAyvLWsBOf+vaZFT2NwseHQPGHp5ftlAwYj0xk/3bJVINa1cgnsK9p+GErrBCI42Bqg5N/O/dhqnuB2136gPW8Ph4Jd6yINO58NImQ6ofC2Jg35MdNb5G9ceBqn5j+77ze1eLPwlaOTDZ9g5c1GzzUx6RPrzxP8OUqLctxgXdOaIUGFyet4raeP/aeGeJGndfdCbhhjjbSeLGH2se/HFd1y57YtMfTmYSKcy2PHqe1g9kWqrBsbOLzsaDO6dme56J2HZWTv0Qwz7f2scs9Lx6OgT0g9JU02vieVrjfzPmhqoT4rQ+D5ssCW5Qv34ygJepKHD4AIWWciitc=
  skip_cleanup: true

branches:
  only: 
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/


